---
#-------------------------------
# General Site Settings

title: Colin Allen
logo:
author: themefisher
description: A website displaying me, Colin Allen
email: colinallen0217@gmail.com
phone: NA
# address:
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Projects, link: "/projects" }
  - { name: Resume, link: "/resume" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: colin-allen # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! Iâ€™m Colin, <br> computer scientist<br> and musician <br><br><br>

social:
  #- { icon: "ti-facebook", link: "#" }
  #- { icon: "ti-instagram", link: "#" }
  #- { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Hey there! I'm a 23 year old computer scientist from the Rochester Institute of Technology who finished classes with a 3.3 GPA.  I will have my degree after my next job, which I'm seeking now!  I've been programming since middle school, lead the robotics team to victory in high school, and continued my passion in college.  In my off time, I'm a drummer for the band Cellar Darts.
blurb-btn-link: "/about"
blurb-btn-name: Learn more!

# About Page

# Work Process Section
#work-process:
#  - title: "Research and Plan"
#    icon: "assets/images/icons/plan.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#  - title: "Design and Develop"
#    icon: "assets/images/icons/design.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#  - title: "Deliver"
#    icon: "assets/images/icons/print.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Alex 'Buggy' Bogusta"
    image: "assets/images/band/buggy.png"
    designation: "Guitarist"

  - title: "Me"
    image: "assets/images/band/me.png"
    designation: "Drummer"

  - title: "Liam 'Yom' Obrechta"
    image: "assets/images/band/yom.png"
    designation: "Bassist & Keys"

  - title: "Matthew Correa"
    image: "assets/images/band/matt.png"
    designation: "Guitarist & Vocalist"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: C, color: "#fdb157", value: "90%" }
  - { name: Python, color: "#9473e6", value: "80%" }
  - { name: Java, color: "#bdecf6", value: "75%" }
  - { name: Javascript, color: "#ffbcaa", value: "60%" }
  - { name: Git, color: "#FFB7C3", value: "80%" }
  - { name: Django, color: "#161032", value: "50%" }
  - { name: MIPS Assembly, color: "#313638", value: "70%" }
  - { name: Jekyll, color: "#FF3864", value: "65%" }


#-------------------------------
# Exprerience Section

experience-title: Professional Experience
experience:
  - {
      name: Junior Software Engineer,
      icon: "icon-1.png",
      date: "Sep 2019 - May 2020",
      organization: "Buffalo General Medical Center",
    }
  - {
      name: Associate Software Engineer,
      icon: "icon-2.png",
      date: "Jan 2022 - Aug 2022",
      organization: "LightRiver Software",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelor's in Computer Science (after 15 weeks employment),
      date: "2023",
      gpa: "3.3",
      organization: "Rochester Institute of Technology",
    }

#-------------------------------
# Services Section

# services-title: Services
# services:
#  - {
#      name: UI Design,
#      icon: ti-palette,
#      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#      active: ,# Add true to select section
#    }
#  - {
#      name: UX Design,
#      icon: ti-vector,
#      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
#      active: true, # Add true to select section
#    }
  # - {
  #     name: Interaction Design,
  #     icon: ti-panel,
  #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  #     active: ,# Add true to select section
  #   }

#-------------------------------
# Projects (Section and Page)

# Projects Home Section
projects-home-items:
  - image: "assets/images/projects/item-1.png"
    url: "#"

  - image: "assets/images/projects/item-2.png"
    url: "#"

  - image: "assets/images/projects/item-3.png"
    url: "#"

  - image: "assets/images/projects/item-4.png"
    url: "#"

  - image: "assets/images/projects/item-5.png"
    url: "#"

# projects Page
# projects-label:
#   - { title: "UI/UX Design", type: "design" }
#   - { title: "BRANDING", type: "branding" }
#   - { title: "ILLUSTRATION", type: "illustration" }

# projects-items:
#   - image: "assets/images/projects/item-1.png"
#     url: "#"
#     projects-type:
#       - type: "design"
#       - type: "illustration"

#   - image: "assets/images/projects/item-2.png"
#     url: "#"
#     projects-type:
#       - type: "branding"

#   - image: "assets/images/projects/item-3.png"
#     url: "#"
#     projects-type:
#       - type: "illustration"

#   - image: "assets/images/projects/item-6.png"
#     url: "#"
#     projects-type:
#       - type: "design"
#       - type: "branding"

#   - image: "assets/images/projects/item-8.png"
#     url: "#"
#     projects-type:
#       - type: "illustration"

#   - image: "assets/images/projects/item-5.png"
#     url: "#"
#     projects-type:
#       - type: "design"

#   - image: "assets/images/projects/item-1.png"
#     url: "#"
#     projects-type:
#       - type: "branding"

#   - image: "assets/images/projects/item-3.png"
#     url: "#"
#     projects-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"

#   - image: "assets/images/projects/item-7.png"
#     url: "#"
#     projects-type:
#       - type: "illustration"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

#contact-title: 
#contact-email: colinallen0217@gmail.com
